### PR TITLE
Stream chat response in Assistants

### PR DESCRIPTION
**Pull request by onerinas**
This PR is an attempt to make streaming working in Assistants. 

Feel free to create a new PR or push to the same branch if you want to try different implemention.

With the current changes, usage looks like this:

```ruby
llm = Langchain::LLM::OpenAI.new(api_key: ENV["OPENAI_API_KEY"])

thread = Langchain::Thread.new

Langchain::Assistant.new(llm: llm, thread: thread) do |response_chunk|
  print(response_chunk["delta"]["content"])
end
```

Screenshot of the same logged in a Sidekiq worker:
Screenshot 2024-02-23 at 7 07 54 PM

### CODE REVIEW

**Comment by andreibondarev** [comment]
@onerinas Looks like it works for streaming `tool_calls` as well if you yield:
```
print(response_chunk["delta"]["tool_calls"])
```

Are you planning on finishing this PR?

**Comment by onerinas** [comment]
@andreibondarev That’s good to know it works for tool_calls as well. 

What would be the next steps to make some progress on the PR? I assume these?
- `yield` in tool_calls
- Update usage of Assistant in the methods docs and README
- Specs

I can give it a try. I’m okay with you picking it up as well if you want.

**Comment by andreibondarev** [comment]
@onerinas Go for it!

**Comment by Jellyfishboy** [comment]
Any update for this?

**Comment by onerinas** [comment]
Update on this: I’m not working on the AI project at the moment so no progress on this so far.

**Comment by andreibondarev** [comment]
Closing this PR since https://github.com/patterns-ai-core/langchainrb/pull/760 was merged.

**Pull request closed without merging**
