### PR TITLE
Optionally pass an OpenAI::Client to the Langchain::LLM::OpenAI initializer

### PR DESCRIPTION
**Pull request by josh-lauer**
This allows the user to pass an instantiated `OpenAI::Client` to the `Langchain::LLM::OpenAI` initializer.

This is related to [this comment](https://github.com/patterns-ai-core/langchainrb/pull/504#issuecomment-2338316203).

### CODE REVIEW

**Review by codenamev — APPROVED** [review]
Nice 👍

**Comment by andreibondarev** [comment]
@josh-lauer Thank you for the PR. Sorry for the delay!

Thoughts on changing [this](https://github.com/patterns-ai-core/langchainrb/blob/main/lib/langchain/llm/base.rb#L27) to `attr_accessor :client` and then setting `llm.client = OpenAI::Client.new(...)` directly?

That would allow this type of customization on other `Langchain::LLM::*` classes.

**Comment by josh-lauer** [comment]
> @josh-lauer Thank you for the PR. Sorry for the delay!
> 
> Thoughts on changing [this](https://github.com/patterns-ai-core/langchainrb/blob/main/lib/langchain/llm/base.rb#L27) to `attr_accessor :client` and then setting `llm.client = OpenAI::Client.new(...)` directly?
> 
> That would allow this type of customization on other `Langchain::LLM::*` classes.

I thought about that, though it would mean one would need to instantiate a `Langchain::LLM::OpenAI`, passing it the token and having it build a client that the user would then immediately clobber. It felt clunky to me at the time. However, maybe that's ok for a rare use case like mine. Maybe it's better to not have the OpenAI LLM class not be an exception to the pattern, taking an extra argument. It's your call. If you want we can make this a one-line change.

As long as we have a way of injecting an instrumented client via an interface rather than having to use `instance_variable_set` or similar tricks, i'm happy.

**Comment by andreibondarev** [comment]
> > @josh-lauer Thank you for the PR. Sorry for the delay!
> > Thoughts on changing [this](https://github.com/patterns-ai-core/langchainrb/blob/main/lib/langchain/llm/base.rb#L27) to `attr_accessor :client` and then setting `llm.client = OpenAI::Client.new(...)` directly?
> > That would allow this type of customization on other `Langchain::LLM::*` classes.
> 
> I thought about that, though it would mean one would need to instantiate a `Langchain::LLM::OpenAI`, passing it the token and having it build a client that the user would then immediately clobber. It felt clunky to me at the time. However, maybe that's ok for a rare use case like mine. Maybe it's better to not have the OpenAI LLM class not be an exception to the pattern, taking an extra argument. It's your call. If you want we can make this a one-line change.
> 
> As long as we have a way of injecting an instrumented client via an interface rather than having to use `instance_variable_set` or similar tricks, i'm happy.

Yeah, let's add `attr_accessor :client` if that's okay.

**Comment by andreibondarev** [comment]
@josh-lauer I went ahead and added a quick fix per our conversation: https://github.com/patterns-ai-core/langchainrb/pull/78. Would you please confirm that it fixes your usecase?

**Comment by josh-lauer** [comment]
> @josh-lauer I went ahead and added a quick fix per our conversation: #78. Would you please confirm that it fixes your usecase?

Changing that to an `attr_accessor` would address my issue. Do you want me to leave in the `Langchain::LLM::OpenAI` initializer changes, or take them out and make this a one-liner?

**Comment by andreibondarev** [comment]
@josh-lauer Whoops! I linked the wrong PR previously. Correct one: https://github.com/patterns-ai-core/langchainrb/pull/788.

**Comment by andreibondarev** [comment]
@josh-lauer Closing this PR since I merged https://github.com/patterns-ai-core/langchainrb/pull/788. Thank you! Please let me know if you have any other issues!

**Comment by josh-lauer** [comment]
> @josh-lauer Closing this PR since I merged #788. Thank you! Please let me know if you have any other issues!

Works for me. Thanks for taking care of this!

**Pull request closed without merging**
