### PR TITLE
Langchain::Tool::QuicknodeBitcoin tool that wraps Quicknode's Bitcoin API

### PR DESCRIPTION
**Pull request by acidtib**

### CODE REVIEW

**Review by mattlindsey — CHANGES_REQUESTED** [review]
I dont know anything about bitcoin, but looks cool.
Noticed a few things:
- Tool methods should have YARD annotations in comments
- Add QUICKNODE_BITCOIN_URL to `.sample.env`
- Add  `quicknode_bitcoin` to list of Available Tools in README

**Comment by acidtib** [comment]
hey @mattlindsey thanks for the comments, the latest commits should take care of things, it was a blast adding the tool, heres a little demo using the example https://asciinema.org/a/656460

**Comment by andreibondarev** [comment]
@acidtib Does it make sense to package it up in a separate gem like `langchainrb-quicknode-bitcoin`? It feels like a very specific tool for people that are in that space.

**Comment by andreibondarev** [comment]
I don't think this tool belongs in the core project.

**Pull request closed without merging**
