### PR TITLE
Update google_vertex_ai.rb

### PR DESCRIPTION
**Pull request by palladius**
Remove the tool_choice line as it breaks Gemini Function Calling. Removing it solves it.

### CODE REVIEW

**Comment by andreibondarev** [comment]
@palladius This is already fixed. Does Vertex AI API actually accept the tool_choice option?

**Comment by palladius** [comment]
I don't know what to say. 

By googling it seems its an openAI thing: https://platform.openai.com/docs/guides/function-calling 

But it also seems to be supported by gemini, look: https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/function-calling 

so my tiepid answer wqould be YES.

**Comment by palladius** [comment]
Note the code error is NOT at API level, it is at Ruby code level (trying to upcase a hash). 
So it seems to me a bug in your code, rather than a missing thing on Gemini side.

Can you explain to me what you were trying to achieve with  

```ruby
params[:tool_choice] = {function_calling_config: {mode: params[:tool_choice].upcase}} if params[:tool_choice]
``` 

? It seems to me like the  params[:tool_choice] you're actually passing is a hash instead of a string. Want me to file a bug to make it clearer?

**Comment by andreibondarev** [comment]
This was already fixed.

**Pull request closed without merging**
